### ISSUE TITLE
Patch 10.2.5 lua error

### ISSUE THREAD

**Issue by TreizeEU** [enderneko/DurabilityAndItemLevel#4]
Since patch 10.2.5 went live this week, the item level on items in my bags doesn't work anymore.

Below is also a new lua error since release, not sure if that's related.

`10x ...faceDurabilityAndItemLevel/ItemLevel_Bag.lua:121: bad argument #1 to "ipairs" (table expected, got nil)
[string "=[C]"]: in function "ipairs"
[string "@DurabilityAndItemLevel/ItemLevel_Bag.lua"]:121: in function <...faceDurabilityAndItemLevel/ItemLevel_Bag.lua:66>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1`

**Comment by enderneko** [comment]
fixed

**Comment by TreizeEU** [comment]
I downloaded this new version. Item level were still not shown in my bags, so I commented out the 4 lines about Baggins, since that's what I also use for bag addon (because I didn't want the item levels shown in Baggins because of its size), and item levels are back in my regular bag.

Thank you. :)
